version: '3.8'

services:
    database:
        image: postgres:latest
        container_name: agro-post
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

        hostname: local
        restart: always
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - '5439:5432'
