version: '3.8'

services:
    database:
        image: postgres:latest
        container_name: agro-post
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

        hostname: local
        restart: always
        volumes:
            - ./src/utils/scripts/init:/docker-entrypoint-initdb.d/
        ports:
            - '5439:5432'
